name: note_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^7.6.4
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  uuid: ^4.1.0
  fl_chart: ^0.65.0
  table_calendar: ^3.0.9
  percent_indicator: ^4.2.3
  pdf: ^3.10.7
  excel: ^4.0.2
  share_plus: ^7.2.2
  open_file: ^3.5.4
  email_validator: ^3.0.0
  provider: ^6.1.5
  permission_handler: ^11.0.1
  android_intent_plus: ^5.3.0
  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  firebase_messaging: ^14.7.21
  cloud_firestore: ^4.15.4
  cloud_functions: ^4.5.1
  mailer: 6.1.1
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  animated_flip_counter: ^0.3.4
  network_info_plus: ^4.1.0
dependency_overrides:
    open_file_macos: any
dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets\icons\keep_up_icon.png
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/image/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/Google Sans/GoogleSans-Regular.ttf
        - asset: assets/fonts/Google Sans/GoogleSans-Medium.ttf
        - asset: assets/fonts/Google Sans/GoogleSans-Bold.ttf
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
